# Site settings
title: Christian Torres
email: chtorrez@gmail.com
description: |
  <p><strong>I am a Senior Mobile and Web<br/> Developer</strong> who also love <br/>Graphic Design.</p>
  <p><strong>Working at <a href="https://nicasource.com" target="_blank">NicaSource</a></strong></p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://christiantorres.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins: []
